export const ethnicity_tooltip = `• Hispanic or Latino - A person of Cuban, Mexican, Puerto Rican, South or Central American, or other Spanish culture or origin regardless of race. \n
• White (not Hispanic or Latino) - A person having origins in any of the original peoples of Europe, the Middle East, or North Africa. \n
• Black or African American (not Hispanic or Latino) - A person having origins in any of the black racial groups of Africa. \n
• Native Hawaiian or Other Pacific Islander (not Hispanic or Latino) - A person having origins in any of the peoples of Hawaii, Guam, Samoa, or other Pacific Islands. \n
• Asian (not Hispanic or Latino) - A person having origins in any of the original peoples of the Far East, Southeast Asia, or the Indian Subcontinent, including, for example, Cambodia, China, India, Japan, Korea, Malaysia, Pakistan, the Philippine Islands, Thailand, and Vietnam. \n
• American Indian or Alaska Native (not Hispanic or Latino) - A person having origins in any of the original peoples of North and South America (including Central America ), and who maintain tribal affiliation or community attachment. \n
• Two or More Races (not Hispanic or Latino) - A person who identifies with more than one of the following, as defined above: White; Black or African American; Native Hawaiian or Other Pacific Islander; Asian; or American Indian or Alaska Native.
    `;

export const disability_tooltip = `Why are you being asked to complete this form? \n
We are a federal contractor or subcontractor. The law requires us to provide equal employment opportunity to qualified people with disabilities. We have a goal of having at least 7% of our workers as people with disabilities. The law says we must measure our progress towards this goal. To do this, we must ask applicants and employees if they have a disability or have ever had one. People can become disabled, so we need to ask this question at least every five years. Completing this form is voluntary, and we hope that you will choose to do so. Your answer is confidential. No one who makes hiring decisions will see it. Your decision to complete the form and your answer will not harm you in any way. If you want to learn more about the law or this form, visit the U.S. Department of Labor’s Office of Federal Contract Compliance Programs (OFCCP) website at www.dol.gov/ofccp. \n
 
How do you know if you have a disability? \n
A disability is a condition that substantially limits one or more of your “major life activities.” If you have or have ever had such a condition, you are a person with a disability. Disabilities include, but are not limited to: • Alcohol or other substance use disorder (not currently using drugs illegally) • Autoimmune disorder, for example, lupus, fibromyalgia, rheumatoid arthritis, HIV/AIDS • Blind or low vision • Cancer (past or present) • Cardiovascular or heart disease • Celiac disease • Cerebral palsy • Deaf or serious difficulty hearing • Diabetes • Disfigurement, for example, disfigurement caused by burns, wounds, accidents, or congenital disorders • Epilepsy or other seizure disorder • Gastrointestinal disorders, for example, Crohn's Disease, irritable bowel syndrome • Intellectual or developmental disability • Mental health conditions, for example, depression, bipolar disorder, anxiety disorder, schizophrenia, PTSD • Missing limbs or partially missing limbs • Mobility impairment, benefiting from the use of a wheelchair, scooter, walker, leg brace(s) and/or other supports • Nervous system condition, for example, migraine headaches, Parkinson’s disease, multiple sclerosis (MS) • Neurodivergence, for example, attention-deficit/hyperactivity disorder (ADHD), autism spectrum disorder, dyslexia, dyspraxia, other learning disabilities • Partial or complete paralysis (any cause) • Pulmonary or respiratory conditions, for example, tuberculosis, asthma, emphysema • Short stature (dwarfism) • Traumatic brain injury `;

export const veteran_tooltip = `Am I a Protected Veteran? \n
What Categories of Veterans Are “Protected” by VEVRAA? \n
“Protected” veterans include the following categories: (1) disabled veterans; (2) recently separated veterans; (3) active duty wartime or campaign badge veterans; and (4) Armed Forces service medal veterans. These categories are defined below. \n
A “disabled veteran” is one of the following: \n
    a veteran of the U.S. military, ground, naval or air service who is entitled to compensation (or who but for the receipt of military retired pay would be entitled to compensation) under laws administered by the Secretary of Veterans Affairs; or \n
    a person who was discharged or released from active duty because of a service-connected disability. \n
A “recently separated veteran” means any veteran during the three-year period beginning on the date of such veteran's discharge or release from active duty in the U.S. military, ground, naval, or air service. \n
An “active duty wartime or campaign badge veteran” means a veteran who served on active duty in the U.S. military, ground, naval or air service during a war, or in a campaign or expedition for which a campaign badge has been authorized under the laws administered by the Department of Defense. \n
An “Armed forces service medal veteran” means a veteran who, while serving on active duty in the U.S. military, ground, naval or air service, participated in a United States military operation for which an Armed Forces service medal was awarded pursuant to Executive Order 12985. `;
